[package]
name = "xenonauts-soldier-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
hex-literal = "0.4.1"
iced = "0.12.1"
iced_aw = { version = "0.9.3", default-features = false, features = ["icons", "number_input"] }
nom = "7.1.3"
rayon = "1.10.0"
rfd = "0.14.1"
rust_search = "2.1.0"
